config/routes.rb
Sample::Application.routes.draw do

  get "welcome/index"

  resources :posts do
    resources :comments
  end

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

	def self.display_data(page, sort)
		self.all
#		self.paginate(:page => page,
#				  :per_page => 10,
#				  :order => sort.nil? ? self.primary_key : sort)
#		#can also include :joins and :conditions
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def new
  @post = Post.new
end

def create
  @post = Post.new(post_params)

  if @post.save
    redirect_to @post
  else
    render 'new'
  end
end

def edit
  @post = Post.find(params[:id])
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end

def show
  @post = Post.find(params[:id])
end

def index
  @posts = Post.display_data(params[:page], params[:sort])
end

def update
  @post = Post.find(params[:id])

  if @post.update(params[:post].permit(:title, :text))
    redirect_to @post
  else
    render 'edit'
  end
end

private
  def post_params
    params.require(:post).permit(:title, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
load '../static/DomainHelper.rb'

module ApplicationHelper
	def tableless_page(*args)
		if args.size == 3
			tableless_page_private(args[0], "", args[1], args[2])
		else
			tableless_page_private(args[0], "/" + args[1], args[2], args[3])
		end
	end

	# =========================================================================
	private #methods
	# =========================================================================

	def navbar_items
		[
			['Posts', 'posts'],
		]
	end

	def current_navbar
	'Posts'
	end

	def current_header
	'Posts On Rails'
	end

	def left_menu_items
		[
			['Posts', '/posts'],
		]
	end

	def left_menu(url_root)
		rValue = '<ul>'
		left_menu_items.each {|x| rValue += '<li><a href="' + url_root + (x[1]) + '">' + (x[0]) + '</a></li>' }
		rValue += '</ul>'
	end

	def header(right_text, right_link)
		site=''
		navbar_items.each {|x| site += x[0] == current_navbar ? x[1] : ''}
		rValue ='
	  <div class="header">
	    <div class="left-header"><image class="ruby-icon" src="/static/images/rails.gif"></image></div>
	    <div class="machine-header"><ul>'
	    DomainHelper.machine_menu_items.each {|x| rValue += '<li><a href="http:/' + x[1] + '/' + site + '">' + x[0] + '</a></li>' }
		rValue += '
	    </ul></div>
	    <div class="centre-header"><h1>' + current_header + '</h1></div>
	    <div class="right-header"><a href="' + right_link + '">' + right_text + '</a></div>
	  </div>
	  <div class="tab-header">
		<ul id="navbar">'

		navbar_items.each {|x| rValue += x[0] == current_navbar ?
			('<li><a class="current">' + x[0] + '</a></li>') :
			('<li><a href="http://' + ENV['SERVER_NAME'] + '/' + x[1] + '">' + (x[0]) + '</a></li>') }

		rValue += '
		</ul>
	  </div>
	'
	end

	def footer
		l = 'Rails'
	    if Rails::env == 'development'
	      l = link_to 'Rails', controller: 'rails/info', action: 'properties'
		end
		'
		  <div class="footer">
			<div class="left-footer">Copyright &copy;' + Time.now.year.to_s + ' Derek Knight</div>
			<div class="right-footer">Powered by Ruby on ' + l + ' (' + Rails::env + '). [Ruby ' + RUBY_VERSION + ', Rails ' + Rails::VERSION::STRING + ']</div>
		  </div>
		'
	end

	def tableless_page_private(right_text, right_link, error_message, yield_data)
	url_root = 	'http://' + request.host_with_port + Rails::configuration.action_controller.relative_url_root
	header(right_text, url_root+right_link) +
	'
	  <div class="page-content">
		<div class="left-menu">
		  ' + left_menu(url_root) + '
		</div>
		<div class="right-content">
		  <br/>
		  <div class="error-content">
			<p style="color: green">' + (error_message.nil? ? "" : error_message) + '</p>
		  </div>
		  <br/>
		  <div class="page-data">
			' + yield_data + '
		  </div>
		</div>
	  </div>

	  ' + footer
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1 class="header">Sample Rails Application</h1>

<%= yield %>

 <div class="footer">
	<div class="left-footer">Copyright &copy;<%= Time.now.year.to_s %> Derek Knight</div>
	<div class="right-footer"><%= link_to "Sample", controller: "welcome" %> Powered by Ruby on <%= link_to "Rails", controller: "rails/info", action: "properties" %> (<%= Rails::env =%>). [Ruby <%= RUBY_VERSION %>, Rails <%= Rails::VERSION::STRING%>]</div>
 </div>

</body>

</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Posts: <%= controller.action_name %></title>
    <link href="/static/stylesheets/scaffold.css" media="screen" rel="Stylesheet" type="text/css" />
  </head>
  <body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
    <%== tableless_page("About", "about", flash[:notice], yield) %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit post</h2>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>Listing posts</h2>

<%= link_to 'New post', new_post_path %>

<table>
  <tr>
    <th width=100px align=left>Title</th>
    <th width=300px align=left>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', post_path(post) %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2>Post</h2>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h3>Comments</h3>
<table>
  <tr>
    <th width=100px align=left>Title</th>
    <th width=300px align=left>Text</th>
    <th></th>
  </tr>

<% @post.comments.each do |comment| %>
  <tr>
    <td><%= comment.commenter %></td>
    <td><%= comment.body %></td>
    <td><!--%= link_to 'Destroy', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %--></td>
  </tr>
<% end %>
</table>

<h3>Add a comment:</h3>
<%= render "comments/form" %>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

app/views/welcome/index.html.erb
<h2>Welcome</h2>
<%= link_to "Posts", controller: "posts" %>